name: diary_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  local_auth: ^2.3.0
  table_calendar: ^3.2.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^3.0.1
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.4.1
  intl: ^0.20.2
  uuid: ^4.5.2
  google_fonts: ^6.3.2
  get_it: ^9.2.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  google_sign_in: ^6.2.1
  image_picker: ^1.2.1
  pdf: ^3.11.1
  printing: ^5.13.4
  share_plus: ^10.1.3
  flutter_quill: ^11.5.0
  http: ^1.2.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
